### ISSUE TITLE
下载后启动报错，找不到 xxxx/src/api/mock/db.json

### ISSUE THREAD

**Issue by mingliao** [BetaRabbit/react-redux-antd-starter#1]
您好，使用您的这个仓库后下载运行 我已经有先cnpm install 了。然后运行 npm  run dev的时候报错了。
Error: ENOENT: no such file or directory, open 'D:\work_place\projects_js\projects_reactjs\redux\react-redux-antd-starte
r\src\api\mock\db.json'
也确实是没有这个文件。

**Comment by betarabbit** [comment]
不好意思，这个是配置的json server的假数据文件，可能是我抽取的时候没有处理干净。。
应该放一个空的json文件就好了

---

发件人: 邦大叔 notifications@github.com
发送时间: 2016年7月11日 10:24:16
收件人: BetaRabbit/react-redux-antd-starter
主题: [BetaRabbit/react-redux-antd-starter] 下载后启动报错，找不到 xxxx/src/api/mock/db.json (#1)

您好，使用您的这个仓库后下载运行 我已经有先cnpm install 了。然后运行 npm run dev的时候报错了。
Error: ENOENT: no such file or directory, open 'D:\work_place\projects_js\projects_reactjs\redux\react-redux-antd-starte
r\src\api\mock\db.json'
也确实是没有这个文件。

―
